using System;
using System.Collections.Generic;

namespace ScreenTimeController
{
    public enum Language
    {
        English,
        SimplifiedChinese,
        TraditionalChinese,
        Japanese,
        Korean,
        Spanish,
        French,
        German,
        Russian,
        Portuguese
    }

    public static class LanguageManager
    {
        private static Language _currentLanguage = Language.English;

        public static Language CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value;
                    LanguageChanged?.Invoke(null, EventArgs.Empty);
                }
            }
        }

        public static event EventHandler LanguageChanged;

        public static string GetLanguageName(Language lang)
        {
            return lang switch
            {
                Language.English => "English",
                Language.SimplifiedChinese => "简体中文",
                Language.TraditionalChinese => "繁體中文",
                Language.Japanese => "日本語",
                Language.Korean => "한국어",
                Language.Spanish => "Español",
                Language.French => "Français",
                Language.German => "Deutsch",
                Language.Russian => "Русский",
                Language.Portuguese => "Português",
                _ => "English"
            };
        }

        public static string GetString(string key)
        {
            return _currentLanguage switch
            {
                Language.SimplifiedChinese => GetSimplifiedChineseString(key),
                Language.TraditionalChinese => GetTraditionalChineseString(key),
                Language.Japanese => GetJapaneseString(key),
                Language.Korean => GetKoreanString(key),
                Language.Spanish => GetSpanishString(key),
                Language.French => GetFrenchString(key),
                Language.German => GetGermanString(key),
                Language.Russian => GetRussianString(key),
                Language.Portuguese => GetPortugueseString(key),
                _ => GetEnglishString(key)
            };
        }

        private static string GetEnglishString(string key)
        {
            return key switch
            {
                "AppTitle" => "Screen Time Controller",
                "Overview" => "Overview",
                "Applications" => "Applications",
                "DailyLimit" => "Daily Limit",
                "UsedToday" => "Used Today",
                "Remaining" => "Remaining",
                "Settings" => "Settings",
                "ApplicationUsage" => "Application Usage:",
                "EnterPassword" => "Enter Password",
                "Password" => "Password:",
                "OK" => "OK",
                "Cancel" => "Cancel",
                "IncorrectPassword" => "Incorrect password. You have {0} attempts left.",
                "TooManyAttempts" => "Too many incorrect attempts. Returning to main screen.",
                "ScreenTimeSettings" => "Screen Time Settings",
                "Sunday" => "Sunday",
                "Monday" => "Monday",
                "Tuesday" => "Tuesday",
                "Wednesday" => "Wednesday",
                "Thursday" => "Thursday",
                "Friday" => "Friday",
                "Saturday" => "Saturday",
                "Hours" => "hours",
                "Minutes" => "minutes",
                "ApplyToAllDays" => "Apply to All Days",
                "PasswordSettings" => "Password Settings",
                "ChangePassword" => "Change Password",
                "NewPassword" => "New Password:",
                "ConfirmPassword" => "Confirm Password:",
                "RemovePassword" => "Remove Password",
                "PasswordEmpty" => "Password cannot be empty.",
                "PasswordMismatch" => "New password and confirmation do not match.",
                "PasswordChanged" => "Password changed successfully.",
                "PasswordRemoved" => "Password removed successfully.",
                "ConfirmRemovePassword" => "Are you sure you want to remove the password? This will allow anyone to access settings without a password.",
                "Confirm" => "Confirm",
                "AllDaysSet" => "All days have been set to the same time limit.",
                "Info" => "Info",
                "Error" => "Error",
                "Success" => "Success",
                "Warning" => "Warning",
                "ScreenTimeWarning" => "Screen Time Warning",
                "FiveMinutesRemaining" => "You have 5 minutes of screen time remaining.",
                "ScreenTimeLimit" => "Screen Time Limit",
                "TimeLimitReached" => "Your daily screen time limit has been reached. The screen will be locked.",
                "MinimizedToTray" => "Application minimized to tray.",
                "ClickToOpen" => "Application minimized to tray. Click to open.",
                "AlreadyRunning" => "Screen Time Controller is already running!\n\nThe existing window has been brought to the front.",
                "AlreadyRunningTitle" => "Application Already Running",
                "Language" => "Language",
                "Exit" => "Exit",
                "Open" => "Open",
                "Unlock" => "Unlock",
                "TimeExpired" => "Screen time has expired",
                "EnterPasswordToUnlock" => "Enter password to unlock",
                "AddBonusTime" => "Add Bonus Time",
                "BonusTimeAdded" => "Bonus time added: {0} minutes",
                "SelectBonusTime" => "Select bonus time:",
                "5Minutes" => "5 minutes",
                "10Minutes" => "10 minutes",
                "15Minutes" => "15 minutes",
                "30Minutes" => "30 minutes",
                "1Hour" => "1 hour",
                "BonusTimeRemaining" => "Bonus time remaining: {0}",
                _ => key
            };
        }

        private static string GetSimplifiedChineseString(string key)
        {
            return key switch
            {
                "AppTitle" => "屏幕时间控制器",
                "Overview" => "概览",
                "Applications" => "应用程序",
                "DailyLimit" => "每日限制",
                "UsedToday" => "今日已用",
                "Remaining" => "剩余时间",
                "Settings" => "设置",
                "ApplicationUsage" => "应用程序使用时间：",
                "EnterPassword" => "输入密码",
                "Password" => "密码：",
                "OK" => "确定",
                "Cancel" => "取消",
                "IncorrectPassword" => "密码错误。您还有 {0} 次尝试机会。",
                "TooManyAttempts" => "尝试次数过多。返回主界面。",
                "ScreenTimeSettings" => "屏幕时间设置",
                "Sunday" => "星期日",
                "Monday" => "星期一",
                "Tuesday" => "星期二",
                "Wednesday" => "星期三",
                "Thursday" => "星期四",
                "Friday" => "星期五",
                "Saturday" => "星期六",
                "Hours" => "小时",
                "Minutes" => "分钟",
                "ApplyToAllDays" => "应用到所有天",
                "PasswordSettings" => "密码设置",
                "ChangePassword" => "更改密码",
                "NewPassword" => "新密码：",
                "ConfirmPassword" => "确认密码：",
                "RemovePassword" => "删除密码",
                "PasswordEmpty" => "密码不能为空。",
                "PasswordMismatch" => "新密码和确认密码不匹配。",
                "PasswordChanged" => "密码更改成功。",
                "PasswordRemoved" => "密码已删除。",
                "ConfirmRemovePassword" => "确定要删除密码吗？这将允许任何人无需密码即可访问设置。",
                "Confirm" => "确认",
                "AllDaysSet" => "所有天已设置为相同的时间限制。",
                "Info" => "信息",
                "Error" => "错误",
                "Success" => "成功",
                "Warning" => "警告",
                "ScreenTimeWarning" => "屏幕时间警告",
                "FiveMinutesRemaining" => "您还剩5分钟的屏幕时间。",
                "ScreenTimeLimit" => "屏幕时间限制",
                "TimeLimitReached" => "您已达到每日屏幕时间限制。屏幕将被锁定。",
                "MinimizedToTray" => "应用程序已最小化到托盘。",
                "ClickToOpen" => "应用程序已最小化到托盘。点击打开。",
                "AlreadyRunning" => "屏幕时间控制器已在运行！\n\n已将现有窗口置于前台。",
                "AlreadyRunningTitle" => "应用程序已在运行",
                "Language" => "语言",
                "Exit" => "退出",
                "Open" => "打开",
                "Unlock" => "解锁",
                "TimeExpired" => "屏幕时间已用完",
                "EnterPasswordToUnlock" => "输入密码以解锁",
                "AddBonusTime" => "添加额外时间",
                "BonusTimeAdded" => "已添加额外时间：{0} 分钟",
                "SelectBonusTime" => "选择额外时间：",
                "5Minutes" => "5 分钟",
                "10Minutes" => "10 分钟",
                "15Minutes" => "15 分钟",
                "30Minutes" => "30 分钟",
                "1Hour" => "1 小时",
                "BonusTimeRemaining" => "剩余额外时间：{0}",
                _ => key
            };
        }

        private static string GetTraditionalChineseString(string key)
        {
            return key switch
            {
                "AppTitle" => "螢幕時間控制器",
                "Overview" => "概覽",
                "Applications" => "應用程式",
                "DailyLimit" => "每日限制",
                "UsedToday" => "今日已用",
                "Remaining" => "剩餘時間",
                "Settings" => "設定",
                "ApplicationUsage" => "應用程式使用時間：",
                "EnterPassword" => "輸入密碼",
                "Password" => "密碼：",
                "OK" => "確定",
                "Cancel" => "取消",
                "IncorrectPassword" => "密碼錯誤。您還有 {0} 次嘗試機會。",
                "TooManyAttempts" => "嘗試次數過多。返回主介面。",
                "ScreenTimeSettings" => "螢幕時間設定",
                "Sunday" => "星期日",
                "Monday" => "星期一",
                "Tuesday" => "星期二",
                "Wednesday" => "星期三",
                "Thursday" => "星期四",
                "Friday" => "星期五",
                "Saturday" => "星期六",
                "Hours" => "小時",
                "Minutes" => "分鐘",
                "ApplyToAllDays" => "應用到所有天",
                "PasswordSettings" => "密碼設定",
                "ChangePassword" => "變更密碼",
                "NewPassword" => "新密碼：",
                "ConfirmPassword" => "確認密碼：",
                "RemovePassword" => "刪除密碼",
                "PasswordEmpty" => "密碼不能為空。",
                "PasswordMismatch" => "新密碼和確認密碼不匹配。",
                "PasswordChanged" => "密碼變更成功。",
                "PasswordRemoved" => "密碼已刪除。",
                "ConfirmRemovePassword" => "確定要刪除密碼嗎？這將允許任何人無需密碼即可存取設定。",
                "Confirm" => "確認",
                "AllDaysSet" => "所有天已設定為相同的時間限制。",
                "Info" => "資訊",
                "Error" => "錯誤",
                "Success" => "成功",
                "Warning" => "警告",
                "ScreenTimeWarning" => "螢幕時間警告",
                "FiveMinutesRemaining" => "您還剩5分鐘的螢幕時間。",
                "ScreenTimeLimit" => "螢幕時間限制",
                "TimeLimitReached" => "您已達到每日螢幕時間限制。螢幕將被鎖定。",
                "MinimizedToTray" => "應用程式已最小化到系統匣。",
                "ClickToOpen" => "應用程式已最小化到系統匣。點擊開啟。",
                "AlreadyRunning" => "螢幕時間控制器已在執行！\n\n已將現有視窗置於前景。",
                "AlreadyRunningTitle" => "應用程式已在執行",
                "Language" => "語言",
                "Exit" => "結束",
                "Open" => "開啟",
                "Unlock" => "解鎖",
                "TimeExpired" => "螢幕時間已用完",
                "EnterPasswordToUnlock" => "輸入密碼以解鎖",
                "AddBonusTime" => "新增額外時間",
                "BonusTimeAdded" => "已新增額外時間：{0} 分鐘",
                "SelectBonusTime" => "選擇額外時間：",
                "5Minutes" => "5 分鐘",
                "10Minutes" => "10 分鐘",
                "15Minutes" => "15 分鐘",
                "30Minutes" => "30 分鐘",
                "1Hour" => "1 小時",
                "BonusTimeRemaining" => "剩餘額外時間：{0}",
                _ => key
            };
        }

        private static string GetJapaneseString(string key)
        {
            return key switch
            {
                "AppTitle" => "スクリーンタイムコントローラー",
                "Overview" => "概要",
                "Applications" => "アプリケーション",
                "DailyLimit" => "1日の制限",
                "UsedToday" => "今日の使用時間",
                "Remaining" => "残り時間",
                "Settings" => "設定",
                "ApplicationUsage" => "アプリケーションの使用時間：",
                "EnterPassword" => "パスワードを入力",
                "Password" => "パスワード：",
                "OK" => "OK",
                "Cancel" => "キャンセル",
                "IncorrectPassword" => "パスワードが正しくありません。あと{0}回試行できます。",
                "TooManyAttempts" => "試行回数が多すぎます。メイン画面に戻ります。",
                "ScreenTimeSettings" => "スクリーンタイム設定",
                "Sunday" => "日曜日",
                "Monday" => "月曜日",
                "Tuesday" => "火曜日",
                "Wednesday" => "水曜日",
                "Thursday" => "木曜日",
                "Friday" => "金曜日",
                "Saturday" => "土曜日",
                "Hours" => "時間",
                "Minutes" => "分",
                "ApplyToAllDays" => "すべての日に適用",
                "PasswordSettings" => "パスワード設定",
                "ChangePassword" => "パスワード変更",
                "NewPassword" => "新しいパスワード：",
                "ConfirmPassword" => "パスワード確認：",
                "RemovePassword" => "パスワード削除",
                "PasswordEmpty" => "パスワードを空にすることはできません。",
                "PasswordMismatch" => "新しいパスワードと確認が一致しません。",
                "PasswordChanged" => "パスワードが変更されました。",
                "PasswordRemoved" => "パスワードが削除されました。",
                "ConfirmRemovePassword" => "パスワードを削除してもよろしいですか？誰でもパスワードなしで設定にアクセスできるようになります。",
                "Confirm" => "確認",
                "AllDaysSet" => "すべての日が同じ時間制限に設定されました。",
                "Info" => "情報",
                "Error" => "エラー",
                "Success" => "成功",
                "Warning" => "警告",
                "ScreenTimeWarning" => "スクリーンタイム警告",
                "FiveMinutesRemaining" => "スクリーンタイムはあと5分です。",
                "ScreenTimeLimit" => "スクリーンタイム制限",
                "TimeLimitReached" => "1日のスクリーンタイム制限に達しました。画面がロックされます。",
                "MinimizedToTray" => "アプリケーションがトレイに最小化されました。",
                "ClickToOpen" => "アプリケーションがトレイに最小化されました。クリックして開きます。",
                "AlreadyRunning" => "スクリーンタイムコントローラーは既に実行中です！\n\n既存のウィンドウが前面に表示されました。",
                "AlreadyRunningTitle" => "アプリケーションは既に実行中です",
                "Language" => "言語",
                "Exit" => "終了",
                "Open" => "開く",
                "Unlock" => "ロック解除",
                "TimeExpired" => "スクリーンタイムが終了しました",
                "EnterPasswordToUnlock" => "ロック解除のパスワードを入力",
                "AddBonusTime" => "ボーナスタイムを追加",
                "BonusTimeAdded" => "ボーナスタイム追加: {0} 分",
                "SelectBonusTime" => "ボーナスタイムを選択:",
                "5Minutes" => "5 分",
                "10Minutes" => "10 分",
                "15Minutes" => "15 分",
                "30Minutes" => "30 分",
                "1Hour" => "1 時間",
                "BonusTimeRemaining" => "残りボーナスタイム: {0}",
                _ => key
            };
        }

        private static string GetKoreanString(string key)
        {
            return key switch
            {
                "AppTitle" => "스크린 타임 컨트롤러",
                "Overview" => "개요",
                "Applications" => "애플리케이션",
                "DailyLimit" => "일일 제한",
                "UsedToday" => "오늘 사용 시간",
                "Remaining" => "남은 시간",
                "Settings" => "설정",
                "ApplicationUsage" => "애플리케이션 사용 시간:",
                "EnterPassword" => "비밀번호 입력",
                "Password" => "비밀번호:",
                "OK" => "확인",
                "Cancel" => "취소",
                "IncorrectPassword" => "비밀번호가 올바르지 않습니다. {0}번 더 시도할 수 있습니다.",
                "TooManyAttempts" => "시도 횟수가 너무 많습니다. 메인 화면으로 돌아갑니다.",
                "ScreenTimeSettings" => "스크린 타임 설정",
                "Sunday" => "일요일",
                "Monday" => "월요일",
                "Tuesday" => "화요일",
                "Wednesday" => "수요일",
                "Thursday" => "목요일",
                "Friday" => "금요일",
                "Saturday" => "토요일",
                "Hours" => "시간",
                "Minutes" => "분",
                "ApplyToAllDays" => "모든 요일에 적용",
                "PasswordSettings" => "비밀번호 설정",
                "ChangePassword" => "비밀번호 변경",
                "NewPassword" => "새 비밀번호:",
                "ConfirmPassword" => "비밀번호 확인:",
                "RemovePassword" => "비밀번호 삭제",
                "PasswordEmpty" => "비밀번호는 비워둘 수 없습니다.",
                "PasswordMismatch" => "새 비밀번호와 확인이 일치하지 않습니다.",
                "PasswordChanged" => "비밀번호가 변경되었습니다.",
                "PasswordRemoved" => "비밀번호가 삭제되었습니다.",
                "ConfirmRemovePassword" => "비밀번호를 삭제하시겠습니까? 누구나 비밀번호 없이 설정에 액세스할 수 있습니다.",
                "Confirm" => "확인",
                "AllDaysSet" => "모든 요일이 동일한 시간 제한으로 설정되었습니다.",
                "Info" => "정보",
                "Error" => "오류",
                "Success" => "성공",
                "Warning" => "경고",
                "ScreenTimeWarning" => "스크린 타임 경고",
                "FiveMinutesRemaining" => "스크린 타임이 5분 남았습니다.",
                "ScreenTimeLimit" => "스크린 타임 제한",
                "TimeLimitReached" => "일일 스크린 타임 제한에 도달했습니다. 화면이 잠깁니다.",
                "MinimizedToTray" => "애플리케이션이 트레이로 최소화되었습니다.",
                "ClickToOpen" => "애플리케이션이 트레이로 최소화되었습니다. 클릭하여 엽니다.",
                "AlreadyRunning" => "스크린 타임 컨트롤러가 이미 실행 중입니다!\n\n기존 창이 전면에 표시되었습니다.",
                "AlreadyRunningTitle" => "애플리케이션이 이미 실행 중입니다",
                "Language" => "언어",
                "Exit" => "종료",
                "Open" => "열기",
                "Unlock" => "잠금 해제",
                "TimeExpired" => "스크린 타임이 만료되었습니다",
                "EnterPasswordToUnlock" => "잠금 해제 비밀번호 입력",
                "AddBonusTime" => "보너스 시간 추가",
                "BonusTimeAdded" => "보너스 시간 추가: {0} 분",
                "SelectBonusTime" => "보너스 시간 선택:",
                "5Minutes" => "5 분",
                "10Minutes" => "10 분",
                "15Minutes" => "15 분",
                "30Minutes" => "30 분",
                "1Hour" => "1 시간",
                "BonusTimeRemaining" => "남은 보너스 시간: {0}",
                _ => key
            };
        }

        private static string GetSpanishString(string key)
        {
            return key switch
            {
                "AppTitle" => "Controlador de Tiempo de Pantalla",
                "Overview" => "Resumen",
                "Applications" => "Aplicaciones",
                "DailyLimit" => "Límite Diario",
                "UsedToday" => "Usado Hoy",
                "Remaining" => "Restante",
                "Settings" => "Configuración",
                "ApplicationUsage" => "Uso de Aplicaciones:",
                "EnterPassword" => "Introducir Contraseña",
                "Password" => "Contraseña:",
                "OK" => "Aceptar",
                "Cancel" => "Cancelar",
                "IncorrectPassword" => "Contraseña incorrecta. Le quedan {0} intentos.",
                "TooManyAttempts" => "Demasiados intentos incorrectos. Volviendo a la pantalla principal.",
                "ScreenTimeSettings" => "Configuración de Tiempo de Pantalla",
                "Sunday" => "Domingo",
                "Monday" => "Lunes",
                "Tuesday" => "Martes",
                "Wednesday" => "Miércoles",
                "Thursday" => "Jueves",
                "Friday" => "Viernes",
                "Saturday" => "Sábado",
                "Hours" => "horas",
                "Minutes" => "minutos",
                "ApplyToAllDays" => "Aplicar a Todos los Días",
                "PasswordSettings" => "Configuración de Contraseña",
                "ChangePassword" => "Cambiar Contraseña",
                "NewPassword" => "Nueva Contraseña:",
                "ConfirmPassword" => "Confirmar Contraseña:",
                "RemovePassword" => "Eliminar Contraseña",
                "PasswordEmpty" => "La contraseña no puede estar vacía.",
                "PasswordMismatch" => "La nueva contraseña y la confirmación no coinciden.",
                "PasswordChanged" => "Contraseña cambiada exitosamente.",
                "PasswordRemoved" => "Contraseña eliminada exitosamente.",
                "ConfirmRemovePassword" => "¿Está seguro de que desea eliminar la contraseña? Esto permitirá que cualquiera acceda a la configuración sin contraseña.",
                "Confirm" => "Confirmar",
                "AllDaysSet" => "Todos los días han sido configurados con el mismo límite de tiempo.",
                "Info" => "Información",
                "Error" => "Error",
                "Success" => "Éxito",
                "Warning" => "Advertencia",
                "ScreenTimeWarning" => "Advertencia de Tiempo de Pantalla",
                "FiveMinutesRemaining" => "Le quedan 5 minutos de tiempo de pantalla.",
                "ScreenTimeLimit" => "Límite de Tiempo de Pantalla",
                "TimeLimitReached" => "Ha alcanzado su límite diario de tiempo de pantalla. La pantalla se bloqueará.",
                "MinimizedToTray" => "Aplicación minimizada a la bandeja.",
                "ClickToOpen" => "Aplicación minimizada a la bandeja. Haga clic para abrir.",
                "AlreadyRunning" => "¡El Controlador de Tiempo de Pantalla ya está en ejecución!\n\nLa ventana existente ha sido llevada al frente.",
                "AlreadyRunningTitle" => "Aplicación ya en Ejecución",
                "Language" => "Idioma",
                "Exit" => "Salir",
                "Open" => "Abrir",
                "Unlock" => "Desbloquear",
                "TimeExpired" => "El tiempo de pantalla ha expirado",
                "EnterPasswordToUnlock" => "Ingrese contraseña para desbloquear",
                "AddBonusTime" => "Agregar Tiempo Bonus",
                "BonusTimeAdded" => "Tiempo bonus agregado: {0} minutos",
                "SelectBonusTime" => "Seleccionar tiempo bonus:",
                "5Minutes" => "5 minutos",
                "10Minutes" => "10 minutos",
                "15Minutes" => "15 minutos",
                "30Minutes" => "30 minutos",
                "1Hour" => "1 hora",
                "BonusTimeRemaining" => "Tiempo bonus restante: {0}",
                _ => key
            };
        }

        private static string GetFrenchString(string key)
        {
            return key switch
            {
                "AppTitle" => "Contrôleur de Temps d'Écran",
                "Overview" => "Aperçu",
                "Applications" => "Applications",
                "DailyLimit" => "Limite Quotidienne",
                "UsedToday" => "Utilisé Aujourd'hui",
                "Remaining" => "Restant",
                "Settings" => "Paramètres",
                "ApplicationUsage" => "Utilisation des Applications:",
                "EnterPassword" => "Entrer le Mot de Passe",
                "Password" => "Mot de Passe:",
                "OK" => "OK",
                "Cancel" => "Annuler",
                "IncorrectPassword" => "Mot de passe incorrect. Il vous reste {0} tentatives.",
                "TooManyAttempts" => "Trop de tentatives incorrectes. Retour à l'écran principal.",
                "ScreenTimeSettings" => "Paramètres de Temps d'Écran",
                "Sunday" => "Dimanche",
                "Monday" => "Lundi",
                "Tuesday" => "Mardi",
                "Wednesday" => "Mercredi",
                "Thursday" => "Jeudi",
                "Friday" => "Vendredi",
                "Saturday" => "Samedi",
                "Hours" => "heures",
                "Minutes" => "minutes",
                "ApplyToAllDays" => "Appliquer à Tous les Jours",
                "PasswordSettings" => "Paramètres de Mot de Passe",
                "ChangePassword" => "Changer le Mot de Passe",
                "NewPassword" => "Nouveau Mot de Passe:",
                "ConfirmPassword" => "Confirmer le Mot de Passe:",
                "RemovePassword" => "Supprimer le Mot de Passe",
                "PasswordEmpty" => "Le mot de passe ne peut pas être vide.",
                "PasswordMismatch" => "Le nouveau mot de passe et la confirmation ne correspondent pas.",
                "PasswordChanged" => "Mot de passe changé avec succès.",
                "PasswordRemoved" => "Mot de passe supprimé avec succès.",
                "ConfirmRemovePassword" => "Êtes-vous sûr de vouloir supprimer le mot de passe? Cela permettra à n'importe qui d'accéder aux paramètres sans mot de passe.",
                "Confirm" => "Confirmer",
                "AllDaysSet" => "Tous les jours ont été définis avec la même limite de temps.",
                "Info" => "Information",
                "Error" => "Erreur",
                "Success" => "Succès",
                "Warning" => "Avertissement",
                "ScreenTimeWarning" => "Avertissement de Temps d'Écran",
                "FiveMinutesRemaining" => "Il vous reste 5 minutes de temps d'écran.",
                "ScreenTimeLimit" => "Limite de Temps d'Écran",
                "TimeLimitReached" => "Vous avez atteint votre limite quotidienne de temps d'écran. L'écran sera verrouillé.",
                "MinimizedToTray" => "Application minimisée dans la barre d'état.",
                "ClickToOpen" => "Application minimisée dans la barre d'état. Cliquez pour ouvrir.",
                "AlreadyRunning" => "Le Contrôleur de Temps d'Écran est déjà en cours d'exécution!\n\nLa fenêtre existante a été mise au premier plan.",
                "AlreadyRunningTitle" => "Application Déjà en Cours",
                "Language" => "Langue",
                "Exit" => "Quitter",
                "Open" => "Ouvrir",
                "Unlock" => "Déverrouiller",
                "TimeExpired" => "Le temps d'écran a expiré",
                "EnterPasswordToUnlock" => "Entrez le mot de passe pour déverrouiller",
                "AddBonusTime" => "Ajouter du Temps Bonus",
                "BonusTimeAdded" => "Temps bonus ajouté: {0} minutes",
                "SelectBonusTime" => "Sélectionner le temps bonus:",
                "5Minutes" => "5 minutes",
                "10Minutes" => "10 minutes",
                "15Minutes" => "15 minutes",
                "30Minutes" => "30 minutes",
                "1Hour" => "1 heure",
                "BonusTimeRemaining" => "Temps bonus restant: {0}",
                _ => key
            };
        }

        private static string GetGermanString(string key)
        {
            return key switch
            {
                "AppTitle" => "Bildschirmzeit-Controller",
                "Overview" => "Übersicht",
                "Applications" => "Anwendungen",
                "DailyLimit" => "Tageslimit",
                "UsedToday" => "Heute Verwendet",
                "Remaining" => "Verbleibend",
                "Settings" => "Einstellungen",
                "ApplicationUsage" => "Anwendungsnutzung:",
                "EnterPassword" => "Passwort Eingeben",
                "Password" => "Passwort:",
                "OK" => "OK",
                "Cancel" => "Abbrechen",
                "IncorrectPassword" => "Falsches Passwort. Sie haben noch {0} Versuche.",
                "TooManyAttempts" => "Zu viele falsche Versuche. Rückkehr zum Hauptbildschirm.",
                "ScreenTimeSettings" => "Bildschirmzeit-Einstellungen",
                "Sunday" => "Sonntag",
                "Monday" => "Montag",
                "Tuesday" => "Dienstag",
                "Wednesday" => "Mittwoch",
                "Thursday" => "Donnerstag",
                "Friday" => "Freitag",
                "Saturday" => "Samstag",
                "Hours" => "Stunden",
                "Minutes" => "Minuten",
                "ApplyToAllDays" => "Auf Alle Tage Anwenden",
                "PasswordSettings" => "Passwort-Einstellungen",
                "ChangePassword" => "Passwort Ändern",
                "NewPassword" => "Neues Passwort:",
                "ConfirmPassword" => "Passwort Bestätigen:",
                "RemovePassword" => "Passwort Entfernen",
                "PasswordEmpty" => "Passwort darf nicht leer sein.",
                "PasswordMismatch" => "Neues Passwort und Bestätigung stimmen nicht überein.",
                "PasswordChanged" => "Passwort erfolgreich geändert.",
                "PasswordRemoved" => "Passwort erfolgreich entfernt.",
                "ConfirmRemovePassword" => "Sind Sie sicher, dass Sie das Passwort entfernen möchten? Dies ermöglicht jedem, ohne Passwort auf die Einstellungen zuzugreifen.",
                "Confirm" => "Bestätigen",
                "AllDaysSet" => "Alle Tage wurden auf dasselbe Zeitlimit eingestellt.",
                "Info" => "Info",
                "Error" => "Fehler",
                "Success" => "Erfolg",
                "Warning" => "Warnung",
                "ScreenTimeWarning" => "Bildschirmzeit-Warnung",
                "FiveMinutesRemaining" => "Sie haben noch 5 Minuten Bildschirmzeit.",
                "ScreenTimeLimit" => "Bildschirmzeit-Limit",
                "TimeLimitReached" => "Sie haben Ihr tägliches Bildschirmzeit-Limit erreicht. Der Bildschirm wird gesperrt.",
                "MinimizedToTray" => "Anwendung in die Taskleiste minimiert.",
                "ClickToOpen" => "Anwendung in die Taskleiste minimiert. Klicken zum Öffnen.",
                "AlreadyRunning" => "Bildschirmzeit-Controller läuft bereits!\n\nDas vorhandene Fenster wurde in den Vordergrund gebracht.",
                "AlreadyRunningTitle" => "Anwendung Läuft Bereits",
                "Language" => "Sprache",
                "Exit" => "Beenden",
                "Open" => "Öffnen",
                "Unlock" => "Entsperren",
                "TimeExpired" => "Die Bildschirmzeit ist abgelaufen",
                "EnterPasswordToUnlock" => "Passwort zum Entsperren eingeben",
                "AddBonusTime" => "Bonuszeit Hinzufügen",
                "BonusTimeAdded" => "Bonuszeit hinzugefügt: {0} Minuten",
                "SelectBonusTime" => "Bonuszeit auswählen:",
                "5Minutes" => "5 Minuten",
                "10Minutes" => "10 Minuten",
                "15Minutes" => "15 Minuten",
                "30Minutes" => "30 Minuten",
                "1Hour" => "1 Stunde",
                "BonusTimeRemaining" => "Verbleibende Bonuszeit: {0}",
                _ => key
            };
        }

        private static string GetRussianString(string key)
        {
            return key switch
            {
                "AppTitle" => "Контролер Времени Экрана",
                "Overview" => "Обзор",
                "Applications" => "Приложения",
                "DailyLimit" => "Дневной Лимит",
                "UsedToday" => "Использовано Сегодня",
                "Remaining" => "Осталось",
                "Settings" => "Настройки",
                "ApplicationUsage" => "Использование Приложений:",
                "EnterPassword" => "Введите Пароль",
                "Password" => "Пароль:",
                "OK" => "ОК",
                "Cancel" => "Отмена",
                "IncorrectPassword" => "Неверный пароль. У вас осталось {0} попыток.",
                "TooManyAttempts" => "Слишком много неверных попыток. Возврат к главному экрану.",
                "ScreenTimeSettings" => "Настройки Времени Экрана",
                "Sunday" => "Воскресенье",
                "Monday" => "Понедельник",
                "Tuesday" => "Вторник",
                "Wednesday" => "Среда",
                "Thursday" => "Четверг",
                "Friday" => "Пятница",
                "Saturday" => "Суббота",
                "Hours" => "часов",
                "Minutes" => "минут",
                "ApplyToAllDays" => "Применить ко Всем Дням",
                "PasswordSettings" => "Настройки Пароля",
                "ChangePassword" => "Изменить Пароль",
                "NewPassword" => "Новый Пароль:",
                "ConfirmPassword" => "Подтвердите Пароль:",
                "RemovePassword" => "Удалить Пароль",
                "PasswordEmpty" => "Пароль не может быть пустым.",
                "PasswordMismatch" => "Новый пароль и подтверждение не совпадают.",
                "PasswordChanged" => "Пароль успешно изменен.",
                "PasswordRemoved" => "Пароль успешно удален.",
                "ConfirmRemovePassword" => "Вы уверены, что хотите удалить пароль? Это позволит любому получать доступ к настройкам без пароля.",
                "Confirm" => "Подтвердить",
                "AllDaysSet" => "Все дни установлены с одинаковым лимитом времени.",
                "Info" => "Информация",
                "Error" => "Ошибка",
                "Success" => "Успех",
                "Warning" => "Предупреждение",
                "ScreenTimeWarning" => "Предупреждение о Времени Экрана",
                "FiveMinutesRemaining" => "У вас осталось 5 минут времени экрана.",
                "ScreenTimeLimit" => "Лимит Времени Экрана",
                "TimeLimitReached" => "Вы достигли дневного лимита времени экрана. Экран будет заблокирован.",
                "MinimizedToTray" => "Приложение свернуто в трей.",
                "ClickToOpen" => "Приложение свернуто в трей. Нажмите, чтобы открыть.",
                "AlreadyRunning" => "Контролер Времени Экрана уже запущен!\n\nСуществующее окно было выведено на передний план.",
                "AlreadyRunningTitle" => "Приложение Уже Запущено",
                "Language" => "Язык",
                "Exit" => "Выход",
                "Open" => "Открыть",
                "Unlock" => "Разблокировать",
                "TimeExpired" => "Время экрана истекло",
                "EnterPasswordToUnlock" => "Введите пароль для разблокировки",
                "AddBonusTime" => "Добавить Бонусное Время",
                "BonusTimeAdded" => "Бонусное время добавлено: {0} минут",
                "SelectBonusTime" => "Выберите бонусное время:",
                "5Minutes" => "5 минут",
                "10Minutes" => "10 минут",
                "15Minutes" => "15 минут",
                "30Minutes" => "30 минут",
                "1Hour" => "1 час",
                "BonusTimeRemaining" => "Осталось бонусного времени: {0}",
                _ => key
            };
        }

        private static string GetPortugueseString(string key)
        {
            return key switch
            {
                "AppTitle" => "Controlador de Tempo de Tela",
                "Overview" => "Visão Geral",
                "Applications" => "Aplicativos",
                "DailyLimit" => "Limite Diário",
                "UsedToday" => "Usado Hoje",
                "Remaining" => "Restante",
                "Settings" => "Configurações",
                "ApplicationUsage" => "Uso de Aplicativos:",
                "EnterPassword" => "Digite a Senha",
                "Password" => "Senha:",
                "OK" => "OK",
                "Cancel" => "Cancelar",
                "IncorrectPassword" => "Senha incorreta. Você tem {0} tentativas restantes.",
                "TooManyAttempts" => "Muitas tentativas incorretas. Retornando à tela principal.",
                "ScreenTimeSettings" => "Configurações de Tempo de Tela",
                "Sunday" => "Domingo",
                "Monday" => "Segunda-feira",
                "Tuesday" => "Terça-feira",
                "Wednesday" => "Quarta-feira",
                "Thursday" => "Quinta-feira",
                "Friday" => "Sexta-feira",
                "Saturday" => "Sábado",
                "Hours" => "horas",
                "Minutes" => "minutos",
                "ApplyToAllDays" => "Aplicar a Todos os Dias",
                "PasswordSettings" => "Configurações de Senha",
                "ChangePassword" => "Alterar Senha",
                "NewPassword" => "Nova Senha:",
                "ConfirmPassword" => "Confirmar Senha:",
                "RemovePassword" => "Remover Senha",
                "PasswordEmpty" => "A senha não pode estar vazia.",
                "PasswordMismatch" => "A nova senha e a confirmação não coincidem.",
                "PasswordChanged" => "Senha alterada com sucesso.",
                "PasswordRemoved" => "Senha removida com sucesso.",
                "ConfirmRemovePassword" => "Tem certeza de que deseja remover a senha? Isso permitirá que qualquer pessoa acesse as configurações sem senha.",
                "Confirm" => "Confirmar",
                "AllDaysSet" => "Todos os dias foram definidos com o mesmo limite de tempo.",
                "Info" => "Informação",
                "Error" => "Erro",
                "Success" => "Sucesso",
                "Warning" => "Aviso",
                "ScreenTimeWarning" => "Aviso de Tempo de Tela",
                "FiveMinutesRemaining" => "Você tem 5 minutos de tempo de tela restantes.",
                "ScreenTimeLimit" => "Limite de Tempo de Tela",
                "TimeLimitReached" => "Você atingiu seu limite diário de tempo de tela. A tela será bloqueada.",
                "MinimizedToTray" => "Aplicativo minimizado para a bandeja.",
                "ClickToOpen" => "Aplicativo minimizado para a bandeja. Clique para abrir.",
                "AlreadyRunning" => "O Controlador de Tempo de Tela já está em execução!\n\nA janela existente foi trazida para a frente.",
                "AlreadyRunningTitle" => "Aplicativo Já em Execução",
                "Language" => "Idioma",
                "Exit" => "Sair",
                "Open" => "Abrir",
                "Unlock" => "Desbloquear",
                "TimeExpired" => "O tempo de tela expirou",
                "EnterPasswordToUnlock" => "Digite a senha para desbloquear",
                "AddBonusTime" => "Adicionar Tempo Bônus",
                "BonusTimeAdded" => "Tempo bônus adicionado: {0} minutos",
                "SelectBonusTime" => "Selecione o tempo bônus:",
                "5Minutes" => "5 minutos",
                "10Minutes" => "10 minutos",
                "15Minutes" => "15 minutos",
                "30Minutes" => "30 minutos",
                "1Hour" => "1 hora",
                "BonusTimeRemaining" => "Tempo bônus restante: {0}",
                _ => key
            };
        }
    }
}
